name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tags

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      - run: corepack enable

      - name: Install root project dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build root project
        run: yarn build

      - name: Publish root project to npm
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install d2m dependencies
        run: yarn install
        working-directory: examples/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Check if the published package is available on NPM
      - name: Wait for NPM package availability
        run: |
          for i in {1..10}; do
            if npm info your-package-name > /dev/null 2>&1; then
              echo "Package is available on NPM";
              break;
            else
              echo "Package not available yet, retrying in 30 seconds...";
              sleep 5;
            fi;
          done

      - name: Build d2m project
        run: yarn build
        working-directory: examples/cli

      - name: Publish d2m to npm
        run: yarn publish --access public
        working-directory: examples/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
